# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mae Fang
tagline:             'Web Developer'
description:         'Mae Fang - Blog'
url:                 http://mmmfang.github.io
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Mae Fang
  url:               https://maefang.com
  email:             mae.fang@gmail.com

# Custom vars
version:             1.0.0
